$ vimrc

`$MYVIMRC` is set to the first vimrc file that is found when searching for the vimrc file (Compare → development/vim/script/vimscript/variables/internal/$_MYVIMRC).

{ Default vimrc file

  If no vimrc file is found (and vim is not started with `-u NONE` or `-C`), then vim loads → development/vim/runtime/defaults_vim.

}

{ TODO

  The `SYS_VIMRC_FILE` macro. For Win 32 environments, it seems to be set in
  → development/vim/sources/src/os_dos_h[os_dos.h].

}

sa:
  → Linux/fhs/etc/vim/vimrc

  → development/vim

  The → development/vim/editing/start-up/command-line-options#vim-cmd-line-opt-u[`-u` command line option]

  → development/vim/runtime/macmap_vim: The System gvimrc file for Mac OS X
